export default {
  toggleClosetToBedroomMagnet: 'toggleClosetToBedroomMagnet',
  flashBedroomVanityLight: 'flashBedroomVanityLight',
  placePictureOnMemorial: 'placePictureOnMemorial',
  resetServo: 'resetServo',
  toggleMirror: 'toggleMirror',
  toggleHoleDoor: 'toggleHoleDoor',
  toggleMemorialLight: 'toggleMemorialLight',
  toggleAirConditionerMagnet: 'toggleAirConditionerMagnet',
  toggleHoleExitMagnet: 'toggleHoleExitMagnet',
  toggleDollMagnet: 'toggleDollMagnet',
  throwCutter: 'throwCutter',
  toggleOperativeWallKidsRoom: 'toggleOperativeWallKidsRoom',
  toggleLettersMagnets: 'toggleLettersMagnets',
  flashLightnings: 'flashLightnings',
  dropVase: 'dropVase',
  toggleMomClosetMagnet: 'toggleMomClosetMagnet',
  toggleVitrinaDoor: 'toggleVitrinaDoor',
  toggleVaseServoRelay: 'toggleVaseServoRelay',
  toggleNextToBedLightLeft: 'toggleNextToBedLightLeft',
  toggleNextToBedLightRight: 'toggleNextToBedLightRight',
  toggleKidsRoomLight1: 'toggleKidsRoomLight1',
  toggleKidsRoomLight2: 'toggleKidsRoomLight2',
  toggleKidsRoomLight3: 'toggleKidsRoomLight3',
  toggleBedroomWallLight: 'toggleBedroomWallLight'

};
