export default {
  closetToBedroomRelay: 'closetToBedroomRelay',
  mirrorRelay: 'mirrorRelay',
  holeRelay: 'holeRelay',
  memorialLightRelay: 'memorialLightRelay',
  airConditionerRelay: 'airConditionerRelay',
  holeExitRelay: 'holeExitRelay',
  dollRelay: 'dollRelay',
  airConditionerHatchServo: 'airConditionerHatchServo',
  airConditionerVisherServo: 'airConditionerVisherServo',
  airConditionerServosRelay: 'airConditionerServosRelay',
  operativeWallKidsRoomRelay: 'operativeWallKidsRoomRelay',
  lettersMagnetsRelay: 'lettersMagnetsRelay',
  vanityLightRelay: 'vanityLightRelay',
  vaseServo: 'vaseServo',
  lightningRelay: 'lightningRelay',
  momClosetRelay: 'momClosetRelay',
  operativeVitrinaRelay: 'operativeVitrinaRelay',
  vaseServoRelay: 'vaseServoRelay',
  nextToBedLightLeft: 'nextToBedLightLeft',
  nextToBedLightRight: 'nextToBedLightRight',
  kidsroomLight1: 'kidsroomLight1',
  kidsroomLight2: 'kidsroomLight2',
  kidsroomLight3: 'kidsroomLight3',
  bedroomWallLight: 'bedroomWallLight',
  livingRoomLight1: 'livingRoomLight1',
  livingRoomLight2: 'livingRoomLight2',
  livingRoomLight3: 'livingRoomLight3'

};
