export default {
  bedroomVanityPictureReadswitch: 'bedroomVanityPictureReadswitch',
  bedroomMemorialLightReadswitch: 'bedroomMemorialLightReadswitch',
  kidsroomFamilyReadswitch: 'kidsroomFamilyReadswitch',
  kidsroomDollPictureReadswitch: 'kidsroomDollPictureReadswitch',
  kidsroomPictureDadReadswitch: 'kidsroomPictureDadReadswitch',
  kidsroomKillerPictureReadswitch: 'kidsroomKillerPictureReadswitch',
  kidsroomMomPictureReadswitch: 'kidsroomMomPictureReadswitch',
  kidsroomGhostPictureReadswitch: 'kidsroomGhostPictureReadswitch',
  drawer1Readswitch: 'drawer1Readswitch',
  drawer2Readswitch: 'drawer2Readswitch',
  drawer3Readswitch: 'drawer3Readswitch',
  drawer4Readswitch: 'drawer4Readswitch',
  drawerMovementSensor: 'drawerMovementSensor',
  clockReadswitch1: 'clockReadswitch1',
  clockReadswitch2: 'clockReadswitch2',
  railReadswitch: 'railReadswitch',
  candlestickReadswitch1: 'candlestickReadswitch1',
  candlestickReadswitch2: 'candlestickReadswitch2',
  candlestickReadswitch3: 'candlestickReadswitch3',
  hallwayProximitySensor: 'hallwayProximitySensor'
}
