export default {
  bedroomVanityPictureReadswitch: 'bedroomVanityPictureReadswitch',
  bedroomMemorialLightReadswitch: 'bedroomMemorialLightReadswitch',
  kidsroomPicture1Readswitch: 'kidsroomPicture1Readswitch',
  kidsroomPicture2Readswitch: 'kidsroomPicture2Readswitch',
  kidsroomPicture3Readswitch: 'kidsroomPicture3Readswitch',
  kidsroomPicture4Readswitch: 'kidsroomPicture4Readswitch',
  kidsroomPicture5Readswitch: 'kidsroomPicture5Readswitch',
  kidsroomPicture6Readswitch: 'kidsroomPicture6Readswitch',
  drawer1Readswitch: 'drawer1Readswitch',
  drawer2Readswitch: 'drawer2Readswitch',
  drawer3Readswitch: 'drawer3Readswitch',
  drawer4Readswitch: 'drawer4Readswitch',
  drawerMovementSensor: 'drawerMovementSensor',
  clockReadswitch1: 'clockReadswitch1',
  clockReadswitch2: 'clockReadswitch2',
  railReadswitch: 'railReadswitch',
  candlestickReadswitch1: 'candlestickReadswitch1',
  candlestickReadswitch2: 'candlestickReadswitch2',
  candlestickReadswitch3: 'candlestickReadswitch3',
  hallwayProximitySensor: 'hallwayProximitySensor'
}
